version: '3.8'

services:
  joomla:
    build: .
    container_name: joomla
    ports:
      - "8080:80"
    volumes:
      - ./joomla:/var/www/html
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
    depends_on:
      - db
    networks:
      - joomla_network

  db:
    image: mysql:latest
    container_name: joomla_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    networks:
      - joomla_network

volumes:
  db_data:

networks:
  joomla_network:
    driver: bridge